Update reusable.yml

diff --git a/.github/workflows/reusable.yml b/.github/workflows/reusable.yml
--- a/.github/workflows/reusable.yml
+++ b/.github/workflows/reusable.yml
@@ -24,4 +24,38 @@ jobs:
         steps:
             - name: Make curl request
               run: |
-                    echo ${{ secrets.DISCORD_WEBHOOK_URI }}
+                  echo ''
+                  status=$([ "${{ inputs.status }}" == 'true' ] && echo 'failed' || echo 'succeeded')
+                  color=$([ "${{ inputs.status }}" == 'true' ] && echo '16007990' || echo '5763719')
+                  json_payload=$(
+                    cat << EOF
+                  {
+                      "embeds": [
+                            {
+                                "type": "rich",
+                                "title": "Workflow $status",
+                                "description": "${{ inputs.message }}",
+                                "color": "$color",
+                                "fields": [
+                                    {
+                                    "name": "Ref",
+                                    "value": "${{ github.ref }}"
+                                    },
+                                    {
+                                    "name": "URL",
+                                    "value": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+                                    },
+                                    {
+                                    "name": "Event",
+                                    "value": "${{ github.event_name }}"
+                                    }
+                                ],
+                                "footer": {
+                                    "text": "${{ github.actor }}"
+                                }
+                            }
+                      ]
+                  }
+                  EOF
+                  )
+                  curl -H "Content-Type:application/json" -d "$json_payload" ${{ secrets.DISCORD_WEBHOOK_URI }}
