Update reusable.yml

diff --git a/.github/workflows/reusable.yml b/.github/workflows/reusable.yml
--- a/.github/workflows/reusable.yml
+++ b/.github/workflows/reusable.yml
@@ -1,60 +1,59 @@
-name: Send slack notification
+name: Send discord notification
 
 on:
-  workflow_call:
-    inputs:
-      status:
-        description: "Status of job"
-        required: true
-        type: boolean
-      message:
-        description: "Message to send"
-        required: false
-        type: string
-        default: ' '
-    secrets:
-      url:
-        description: "Slack webhook url"
-        required: true
+    workflow_call:
+        inputs:
+            status:
+                description: "Status of job"
+                required: true
+                type: boolean
+            message:
+                description: "Message to send"
+                required: false
+                type: string
+                default: ""
+        secrets:
+            url:
+                description: "Webhook url"
+                required: true
 
 jobs:
-  run:
-    name: Send notification
-    runs-on: ubuntu-latest
-    steps:
-      - name: Make curl request
-        run: |
-          status=$([ "${{ inputs.status }}" == 'true' ] && echo 'failed' || echo 'succeeded')
-          color=$([ "${{ inputs.status }}" == 'true' ] && echo '#f44336' || echo '#66bb6a')
-          json_payload=$(cat << EOF
-          {
-            "attachments": [
-                {
-                    "color": "$color",
-                    "author_name": "${{ github.actor }}",
-                    "author_icon": "https://github.com/${{ github.actor }}.png",
-                    "title": "Workflow <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.workflow }}> $status",
-                    "text": "${{ inputs.message }}",
-                    "fields": [
-                        {
-                            "title": "Ref",
-                            "value": "${{ github.ref_name }}",
-                            "short": true
-                        },
-                        {
-                            "title": "Event",
-                            "value": "${{ github.event_name }}",
-                            "short": true
-                        },
-                        {
-                            "title": "Message",
-                            "value": "${{ inputs.message }}",
-                            "short": false
-                        }
-                    ]
-                }
-            ]
-          }
-          EOF
-          )
-          curl -X POST -H "Content-Type:application/json" -d "$json_payload" ${{ secrets.url }}
+    run:
+        name: Send notification
+        runs-on: ubuntu-latest
+        steps:
+            - name: Make curl request
+              run: |
+                  status=$([ "${{ inputs.status }}" == 'true' ] && echo 'failed' || echo 'succeeded')
+                  color=$([ "${{ inputs.status }}" == 'true' ] && echo '#f44336' || echo '#66bb6a')
+                  json_payload=$(cat << EOF
+                  {
+                      "embeds": [
+                            {
+                                "type": "rich",
+                                "title": "Workflow $status",
+                                "description": "${{ inputs.message }}",
+                                "color": "$color",
+                                "fields": [
+                                    {
+                                    "name": "Ref",
+                                    "value": "${{ github.ref }}"
+                                    },
+                                    {
+                                    "name": "URL",
+                                    "value": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+                                    },
+                                    {
+                                    "name": "Event",
+                                    "value": "${{ github.event_name }}"
+                                    }
+                                ],
+                                "footer": {
+                                    "text": "${{ github.actor }}"
+                                }
+                            }
+                      ]
+                  }
+                  EOF
+                  )
+                  curl -X POST -H "Content-Type:application/json" -d "$json_payload" ${{ secrets.url }}
